.PHONY: clean build_and_run build

clean:
	        rm -rf out

build_and_run:
	        @mkdir -p out
		        gcc -o out/beehive src/*.c
			        out/beehive

build:
	        @mkdir -p out
		        gcc -o out/beehive src/*.c
